'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'EN' | 'FR' | 'NL' | 'DA';

interface LangContextType {
    lang: Lang;
    setLang: (l: Lang) => void;
    t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
    EN: {
        'nav.destinations': 'Destinations',
        'nav.services': 'Services',
        'nav.contact': 'Contact',
        'nav.client_area': 'Client Area',
        'footer.desc': 'Private journeys and concierge services designed for modern travelers.',
        'footer.rights': '© 2026 Luna Conciergerie. All rights reserved.',
        'footer.col1': 'Concierge',
        'footer.private_col': 'Private Collections',
        'footer.services_link': 'Services & Offerings',
        'footer.tailor_made': 'Tailor-Made Creation',
        'footer.client_area': 'Client Area',
        'footer.col2': 'The Experience',
        'footer.our_story': 'Our Story',
        'footer.private_concierge': 'Private Concierge',
        'footer.signature_trips': 'Signature Journeys',
        'footer.testimonials': 'Testimonials',
        'footer.col3': 'Contact',
        'footer.cgv': 'T&C',
        'footer.legal': 'Legal Notice',
        'footer.privacy': 'Privacy',
        'footer.cookies': 'Cookies',
        'hero.title': 'Travel beautifully.<br />Work anywhere.',
        'hero.subtitle': 'Private journeys, exclusive destinations and concierge services designed for modern travelers.',
        'hero.cta': 'Start Planning',
        'dest.subtitle': 'Destinations',
        'dest.title': 'Exceptional Journeys',
        'dest.cta': 'Create a tailor-made stay',
        'dest.explore': 'Explore the journey',
        'cat.subtitle': 'Catalog',
        'cat.title': 'Services & Offerings',
        'cat.empty': 'No services available.',
        'cat.from': 'From',
        'cat.add': 'Add to my project',
        'cat.disclaimer': 'Reservation on request. Subject to availability.',
        'cat.client_price': 'Exclusive Client Rate',
        'form.title': 'Tailor-Made Journey',
        'form.subtitle': 'Let our expert concierges design your ultimate escape.',
        'form.firstname': 'First Name',
        'form.lastname': 'Last Name',
        'form.email': 'Email',
        'form.phone': 'Phone',
        'form.destination': 'Destination Dream',
        'form.dates': 'Expected Dates',
        'form.budget': 'Total Budget (€)',
        'form.pax': 'Travelers (Pax)',
        'form.vibe': 'Vibe',
        'form.notes': 'Special Requests (Notes)',
        'form.notes_ph': 'Tell us more about what would make this trip perfect...',
        'form.btn': 'Send to Luna',
        'form.sending': 'Sending...',
        'form.select': 'Select...',
        'form.success': 'Request Sent!',
        'form.success_desc': 'Your VIP request has been transmitted to our concierge. One of our experts will contact you within 24 hours.',
        'form.another': 'Make another request',
    },
    FR: {
        'nav.destinations': 'Destinations',
        'nav.services': 'Services',
        'nav.contact': 'Contact',
        'nav.client_area': 'Espace Client',
        'footer.desc': 'Voyages privés et services de conciergerie sur-mesure pour les voyageurs exigeants.',
        'footer.rights': '© 2026 Luna Conciergerie. Tous droits réservés.',
        'footer.col1': 'Conciergerie',
        'footer.private_col': 'Collections Privées',
        'footer.services_link': 'Prestations & Services',
        'footer.tailor_made': 'Création Sur-Mesure',
        'footer.client_area': 'Espace Client',
        'footer.col2': 'L\'Expérience',
        'footer.our_story': 'Notre Histoire',
        'footer.private_concierge': 'Conciergerie Privée',
        'footer.signature_trips': 'Voyages Signature',
        'footer.testimonials': 'Témoignages',
        'footer.col3': 'Contact',
        'footer.cgv': 'CGV',
        'footer.legal': 'Mentions Légales',
        'footer.privacy': 'Confidentialité',
        'footer.cookies': 'Cookies',
        'hero.title': 'Voyagez magnifiquement.<br />Travaillez partout.',
        'hero.subtitle': 'Voyages privés, destinations exclusives et services de conciergerie conçus pour les voyageurs modernes.',
        'hero.cta': 'Commencer l\'expérience',
        'dest.subtitle': 'Destinations',
        'dest.title': 'Voyages d\'Exception',
        'dest.cta': 'Créer un séjour sur-mesure',
        'dest.explore': 'Explorer le voyage',
        'cat.subtitle': 'Catalogue',
        'cat.title': 'Prestations & Services',
        'cat.empty': 'Aucun service disponible.',
        'cat.from': 'À partir de',
        'cat.add': 'Ajouter à mon projet',
        'cat.disclaimer': 'Réservation sur demande. Soumis à disponibilité.',
        'cat.client_price': 'Tarif Client Exclusif',
        'form.title': 'Voyage Sur-Mesure',
        'form.subtitle': 'Laissez nos experts concierges concevoir votre évasion ultime.',
        'form.firstname': 'Prénom',
        'form.lastname': 'Nom',
        'form.email': 'Email',
        'form.phone': 'Téléphone',
        'form.destination': 'Destination de Rêve',
        'form.dates': 'Dates Prévues',
        'form.budget': 'Budget Total (€)',
        'form.pax': 'Voyageurs (Pax)',
        'form.vibe': 'Ambiance',
        'form.notes': 'Demandes Spéciales (Notes)',
        'form.notes_ph': 'Dites-nous en plus sur ce qui rendrait ce voyage parfait...',
        'form.btn': 'Envoyer à Luna',
        'form.sending': 'Envoi en cours...',
        'form.select': 'Sélectionner...',
        'form.success': 'Demande Envoyée !',
        'form.success_desc': 'Votre demande VIP a été transmise à notre conciergerie. L\'un de nos experts vous contactera sous 24 heures.',
        'form.another': 'Faire une autre demande',
    },
    NL: {
        'nav.destinations': 'Bestemmingen',
        'nav.services': 'Diensten',
        'nav.contact': 'Contact',
        'nav.client_area': 'Klantenzone',
        'footer.desc': 'Privéreizen en conciërgediensten ontworpen voor moderne reizigers.',
        'footer.rights': '© 2026 Luna Conciergerie. Alle rechten voorbehouden.',
        'footer.col1': 'Conciërge',
        'footer.private_col': 'Privécollecties',
        'footer.services_link': 'Diensten & Aanbod',
        'footer.tailor_made': 'Op Maat Gemaakt',
        'footer.client_area': 'Klantenzone',
        'footer.col2': 'De Ervaring',
        'footer.our_story': 'Ons Verhaal',
        'footer.private_concierge': 'Privé Conciërge',
        'footer.signature_trips': 'Signature Reizen',
        'footer.testimonials': 'Getuigenissen',
        'footer.col3': 'Contact',
        'footer.cgv': 'AV',
        'footer.legal': 'Juridische Info',
        'footer.privacy': 'Privacy',
        'footer.cookies': 'Cookies',
        'hero.title': 'Reis prachtig.<br />Werk overal.',
        'hero.subtitle': 'Privéreizen, exclusieve bestemmingen en conciërgediensten ontworpen voor moderne reizigers.',
        'hero.cta': 'Begin met plannen',
        'dest.subtitle': 'Bestemmingen',
        'dest.title': 'Uitzonderlijke Reizen',
        'dest.cta': 'Creëer een verblijf op maat',
        'dest.explore': 'Ontdek de reis',
        'cat.subtitle': 'Catalogus',
        'cat.title': 'Diensten & Aanbod',
        'cat.empty': 'Geen diensten beschikbaar.',
        'cat.from': 'Vanaf',
        'cat.add': 'Toevoegen aan mijn project',
        'cat.disclaimer': 'Reservering op aanvraag. Afhankelijk van beschikbaarheid.',
        'cat.client_price': 'Exclusief Klantentarief',
        'form.title': 'Reis op Maat',
        'form.subtitle': 'Laat onze deskundige conciërges uw ultieme ontsnapping ontwerpen.',
        'form.firstname': 'Voornaam',
        'form.lastname': 'Achternaam',
        'form.email': 'E-mail',
        'form.phone': 'Telefoon',
        'form.destination': 'Droombestemming',
        'form.dates': 'Verwachte Data',
        'form.budget': 'Totaal Budget (€)',
        'form.pax': 'Reizigers (Pax)',
        'form.vibe': 'Sfeer / Vibe',
        'form.notes': 'Speciale Verzoeken (Opmerkingen)',
        'form.notes_ph': 'Vertel ons meer over wat deze reis perfect zou maken...',
        'form.btn': 'Verstuur naar Luna',
        'form.sending': 'Verzenden...',
        'form.select': 'Selecteer...',
        'form.success': 'Aanvraag Verzonden!',
        'form.success_desc': 'Uw VIP-aanvraag is doorgestuurd naar onze conciërge. Een van onze experts neemt binnen 24 uur contact met u op.',
        'form.another': 'Nog een aanvraag doen',
    },
    DA: {
        'nav.destinations': 'Destinationer',
        'nav.services': 'Tjenester',
        'nav.contact': 'Kontakt',
        'nav.client_area': 'Kundeområde',
        'footer.desc': 'Private rejser og concierge-tjenester designet til moderne rejsende.',
        'footer.rights': '© 2026 Luna Conciergerie. Alle rettigheder forbeholdes.',
        'footer.col1': 'Concierge',
        'footer.private_col': 'Private Samlinger',
        'footer.services_link': 'Tjenester & Tilbud',
        'footer.tailor_made': 'Skræddersyet Oplevelse',
        'footer.client_area': 'Kundeområde',
        'footer.col2': 'Oplevelsen',
        'footer.our_story': 'Vores Historie',
        'footer.private_concierge': 'Privat Concierge',
        'footer.signature_trips': 'Signaturrejser',
        'footer.testimonials': 'Udtalelser',
        'footer.col3': 'Kontakt',
        'footer.cgv': 'Vilkår',
        'footer.legal': 'Juridisk Meddelelse',
        'footer.privacy': 'Privatlivspolitik',
        'footer.cookies': 'Cookies',
        'hero.title': 'Rejs smukt.<br />Arbejd overalt.',
        'hero.subtitle': 'Private rejser, eksklusive destinationer og concierge-tjenester designet til moderne rejsende.',
        'hero.cta': 'Start planlægning',
        'dest.subtitle': 'Destinationer',
        'dest.title': 'Ekstraordinære Rejser',
        'dest.cta': 'Skab et skræddersyet ophold',
        'dest.explore': 'Udforsk rejsen',
        'cat.subtitle': 'Katalog',
        'cat.title': 'Tjenester & Tilbud',
        'cat.empty': 'Ingen tjenester tilgængelige.',
        'cat.from': 'Fra',
        'cat.add': 'Føj til mit projekt',
        'cat.disclaimer': 'Reservation på anmodning. Afhængig af tilgængelighed.',
        'cat.client_price': 'Eksklusiv Kundepris',
        'form.title': 'Skræddersyet Rejse',
        'form.subtitle': 'Lad vores eksperter designe din ultimative flugt.',
        'form.firstname': 'Fornavn',
        'form.lastname': 'Efternavn',
        'form.email': 'E-mail',
        'form.phone': 'Telefon',
        'form.destination': 'Drømmedestination',
        'form.dates': 'Forventede Datoer',
        'form.budget': 'Samlet Budget (€)',
        'form.pax': 'Rejsende (Pax)',
        'form.vibe': 'Stemning / Vibe',
        'form.notes': 'Specielle Anmodninger (Noter)',
        'form.notes_ph': 'Fortæl os mere om, hvad der ville gøre denne rejse perfekt...',
        'form.btn': 'Send til Luna',
        'form.sending': 'Sender...',
        'form.select': 'Vælg...',
        'form.success': 'Anmodning Sendt!',
        'form.success_desc': 'Din VIP-anmodning er overført til vores concierge. En af vores eksperter vil kontakte dig inden for 24 timer.',
        'form.another': 'Lav en ny anmodning',
    }
};

const LangContext = createContext<LangContextType | undefined>(undefined);

export function LangProvider({ children }: { children: ReactNode }) {
    const [lang, setLang] = useState<Lang>('FR');

    const t = (key: string) => {
        return translations[lang][key] || key;
    };

    return (
        <LangContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LangContext.Provider>
    );
}

export function useLang() {
    const context = useContext(LangContext);
    if (!context) throw new Error('useLang must be used within LangProvider');
    return context;
}
